# Generated by Django 3.2.7 on 2021-09-27 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210926_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.tag'),
        ),
    ]
